package eu.alkismavridis.euljava.core.ast.operators

enum class SpecialCharType(val prefixPriority: Int, val infixPriority: Int, val isInfixRtl: Boolean, val suffixPriority: Int) {
    NOT_A_SPECIAL_CHARACTER(-1, -1, false, -1),
    DOT(-1, 20, false, -1),
    TILDE(17, -1, false, -1),
    HASH(-1,  -1, false, -1),
    DOLLAR(-1,  -1, false, -1),
    PARENTHESIS_OPEN(-1,  -1, false, 20),
    PARENTHESIS_CLOSE(-1,  -1, false, -1),
    SQUARE_OPEN(-1,  -1, false, 20),
    SQUARE_CLOSE(-1,  -1, false, -1),
    CURLY_OPEN(-1,  -1, false, -1),
    CURLY_CLOSE(-1,  -1, false, -1),
    COLON(-1,  -1, false, -1),
    SEMICOLON(-1,  -1, false, -1),
    AT(-1,  -1, false, -1),
    QUESTION_MARK(-1,  -1, false, -1),
    COMMA(-1,  -1, false, -1),
    BACKSLASH(-1,  -1, false, -1),
    EQUALS(-1,  3, true, -1),
    DOUBLE_EQUALS(-1,  11, false, -1),
    TRIPLE_EQUALS(-1,  11, false, -1),
    NOT(17,  -1, false, -1),
    NOT_EQUALS(-1,  11, false, -1),
    NOT_DOUBLE_EQUALS(-1,  11, false, -1),
    PLUS(17,  14, false, -1),
    DOUBLE_PLUS(17,  -1, false, 18),
    PLUS_EQUALS(-1,  3, true, -1),
    MINUS(17,  14, false, -1),
    DOUBLE_MINUS(17,  -1, false, 18),
    MINUS_EQUALS(-1,  3, true, -1),
    ARROW(-1,  -1, false, -1),
    STAR(-1,  15, false, -1),
    STAR_EQUALS(-1,  3, true, -1),
    SLASH(-1,  15, false, -1),
    SLASH_EQUALS(-1,  3, true, -1),
    GREATER(-1,  12, false, -1),
    GREATER_EQUALS(-1,  12, false, -1),
    LESS(-1,  12, false, -1),
    LESS_EQUALS(-1,  12, false, -1),
    XOR(-1,  9, false, -1),
    XOR_EQUALS(-1,  3, true, -1),
    PERCENT(-1,  15, false, -1),
    PERCENT_EQUALS(-1,  3, true, -1),
    OR(-1,  8, false, -1),
    DOUBLE_OR(-1,  6, false, -1),
    OR_EQUALS(-1,  3, true, -1),
    AND(-1,  10, false, -1),
    DOUBLE_AND(-1,  7, false, -1),
    AND_EQUALS(-1,  3, true, -1),
    NEW_LINE(-1,  -1, false, -1);

    fun isPrefix() = this.prefixPriority > 0
    fun isInfix() = this.infixPriority > 0
    fun isSuffix() = this.suffixPriority > 0
}
